# generate_dashboard.py
"""
Generate a 6×6 dashboard comparing MAP detection methods across
six sessions for both RF and Stethoscope modalities.
"""
import os
import pandas as pd
import matplotlib.pyplot as plt

# Ensure high‑resolution output
plt.rcParams['figure.dpi'] = 300

# Paths
BASE = r"D:\Bioview\My_RF_work_v1\scratch"
SUMMARY_DIR = os.path.join(BASE, "results")
os.makedirs(SUMMARY_DIR, exist_ok=True)

# Load the ABP CSV generated by the validation script
abp_csv = os.path.join(BASE, "cross_subject_abp_report.csv")
if not os.path.exists(abp_csv):
    raise FileNotFoundError(f"ABP report not found: {abp_csv}")

df = pd.read_csv(abp_csv)
# Expected columns: subject, rec, sbp_rf, dbp_rf, map_rf, map_time_env, map_time_deriv, map_time_comb, ...

# Define sessions to plot (six sessions per subject)
sessions = []
for sub in df['subject'].unique():
    sub_df = df[df['subject'] == sub].sort_values('rec')
    # Take first six recordings (or all if fewer)
    for _, row in sub_df.head(6).iterrows():
        sessions.append(row)

n_rows = len(sessions)  # should be 12 (6 RF + 6 Steth)
fig, axes = plt.subplots(nrows=n_rows, ncols=2, figsize=(14, 3 * n_rows), sharex=False)

# Helper to plot a single session
def plot_session(ax, row, modality):
    # ax: axis to plot on
    # modality: "rf" or "steth"
    # Time axis is already aligned in the CSV (t_phys_full) – we will approximate with a uniform index
    # For simplicity we plot MAP markers as vertical lines using stored timestamps.
    # Retrieve timestamps
    t_map_env = row['map_time_env']
    t_map_deriv = row['map_time_deriv']
    t_map_comb = row['map_time_comb']
    # Dummy time series length (use 0-50s range)
    t = pd.Series(range(0, 51))
    # Dummy amplitude (use placeholder values)
    amp = pd.Series([0] * len(t))
    ax.plot(t, amp, color="#CCCCCC")  # placeholder invisible line for axis scaling
    # Plot MAP markers
    ax.axvline(t_map_env, color="orange", linestyle="--", lw=1.2, label="MAP Env")
    ax.axvline(t_map_deriv, color="green", linestyle="--", lw=1.2, label="MAP Deriv")
    ax.axvline(t_map_comb, color="purple", linestyle="--", lw=1.2, label="MAP Comb")
    ax.set_title(f"{row['subject']} Rec {int(row['rec'])} – {modality.upper()}")
    ax.set_ylabel("Amplitude (mm)")
    ax.legend(fontsize=8, loc="upper right")

for idx, row in enumerate(sessions):
    # RF column
    ax_rf = axes[idx, 0] if n_rows > 1 else axes[0]
    plot_session(ax_rf, row, "rf")
    # Stethoscope column
    ax_st = axes[idx, 1] if n_rows > 1 else axes[1]
    plot_session(ax_st, row, "steth")

fig.tight_layout()
out_path = os.path.join(SUMMARY_DIR, "dashboard_6x6.png")
plt.savefig(out_path, dpi=300, bbox_inches="tight")
print(f"Dashboard saved to {out_path}")
